version: '3.4'

services:
  # catalogdb:
  #   container_name: catalogdb
  #   image: postgres:17
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=CatalogDb
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   restart: always
  #   ports:
  #       - "5435:5432"
  #   volumes:
  #     - postgres_catalog:/var/lib/postgresql/data/ 
      
  # basketdb:
  #   container_name: basketdb
  #   image: postgres:17
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=BasketDb
  #     - POSTGRES_HOST_AUTH_METHOD=trust 
  #   restart: always
  #   ports:
  #       - "5433:5432"
  #   volumes:
  #     - postgres_basket:/var/lib/postgresql/data/ 

  # userdb:
  #   container_name: userdb
  #   image: postgres:17
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=UserDb
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   restart: always
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - postgres_user:/var/lib/postgresql/data/

  # reviewdb:
  #   container_name: reviewdb
  #   image: postgres:17
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=ReviewDb
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   restart: always
  #   ports:
  #     - "5437:5432"
  #   volumes:
  #     - postgres_review:/var/lib/postgresql/data/

  # filedb:
  #   container_name: filedb
  #   image: postgres:17
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=FileDb
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   restart: always
  #   ports:
  #     - "5438:5432"
  #   volumes:
  #     - postgres_file:/var/lib/postgresql/data/

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Quanggiap299@
    restart: always
    ports:
      - "1433:1433"

  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  user.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=ep-withered-mode-abvpn191-pooler.eu-west-2.aws.neon.tech;Database=UserDb;Username=neondb_owner;Password=npg_iI0VlNtHxs7F;SslMode=Require
    # depends_on:
    #   - userdb
    ports:
      - "6006:8080"
      - "6066:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  review.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=ep-snowy-credit-a4ogtygi-pooler.us-east-1.aws.neon.tech;Database=ReviewDb;Username=neondb_owner;Password=npg_DyTZ8Qq9IiOx;SslMode=Require
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      # - reviewdb
      - messagebroker
    ports:
      - "6007:8080"
      - "6067:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  file.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=ep-snowy-credit-a4ogtygi-pooler.us-east-1.aws.neon.tech;Database=FileDb;Username=neondb_owner;Password=npg_DyTZ8Qq9IiOx;SslMode=Require
    # depends_on:
      # - filedb
    ports:
      - "6010:8080"
      - "6070:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=ep-summer-wave-a4okjsea-pooler.us-east-1.aws.neon.tech;Database=CatalogDb;Username=neondb_owner;Password=npg_fXcpTMYN1ky8;SslMode=Require
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest                 
      - MessageBroker__Password=guest
    depends_on:
      # - catalogdb
      - messagebroker
    ports:
      - "6009:8080"
      - "6069:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=ep-summer-wave-a4okjsea-pooler.us-east-1.aws.neon.tech;Database=BasketDb;Username=neondb_owner;Password=npg_fXcpTMYN1ky8;SslMode=Require
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      # - basketdb
      - distributedcache
      - discount.grpc
      - messagebroker
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=ep-withered-mode-abvpn191-pooler.eu-west-2.aws.neon.tech;Database=OrderDb;Username=neondb_owner;Password=npg_iI0VlNtHxs7F;SslMode=Require
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
    depends_on:
      - orderdb
      - messagebroker
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  notification.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=ep-summer-wave-a4okjsea-pooler.us-east-1.aws.neon.tech;Database=NotificationDb;Username=neondb_owner;Password=npg_fXcpTMYN1ky8;SslMode=Require
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
    depends_on:
      - messagebroker
    ports:
      - "6011:8080"
      - "6021:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
      - user.api
      - review.api
      - file.api
      - notification.api
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  shopping.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ApiSettings__GatewayAddress=http://yarpapigateway:8080
    depends_on:
      - yarpapigateway
    ports:
      - "6005:8080"
      - "6065:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
